// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HomeCrud.Test.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class HomeFeaturesFeature : Xunit.IClassFixture<HomeFeaturesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HomeFeatures.feature"
#line hidden
        
        public HomeFeaturesFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Home Features", "\tIn order to manage home data\r\n\tAs a anonymous\r\n\tI want to be able to create, rea" +
                    "d, update and delete homes", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(HomeFeaturesFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Create Home")]
        [Xunit.TraitAttribute("FeatureTitle", "Home Features")]
        [Xunit.TraitAttribute("Description", "Create Home")]
        public virtual void CreateHome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create Home", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "Name",
                        "Peña\'s Home"});
            table1.AddRow(new string[] {
                        "Address",
                        "Test Address"});
#line 7
 testRunner.When("I create a home with the following data", ((string)(null)), table1, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "Name",
                        "Peña\'s Home"});
            table2.AddRow(new string[] {
                        "Address",
                        "Test Address"});
#line 11
 testRunner.Then("should exists a home with data", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="List Homes")]
        [Xunit.TraitAttribute("FeatureTitle", "Home Features")]
        [Xunit.TraitAttribute("Description", "List Homes")]
        public virtual void ListHomes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("List Homes", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "Name",
                        "Fransic\'s Home"});
            table3.AddRow(new string[] {
                        "Address",
                        "Test Address"});
#line 17
 testRunner.Given("I create a home with the following data", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "Name",
                        "Trumps\'s Home"});
            table4.AddRow(new string[] {
                        "Address",
                        "Test Address 2"});
#line 21
 testRunner.And("I create a home with the following data", ((string)(null)), table4, "And ");
#line 25
 testRunner.When("I list the last 2 created homes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Address"});
            table5.AddRow(new string[] {
                        "Fransic\'s Home",
                        "Test Address"});
            table5.AddRow(new string[] {
                        "Trumps\'s Home",
                        "Test Address 2"});
#line 26
 testRunner.Then("the following homes should exists", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="View Home Details")]
        [Xunit.TraitAttribute("FeatureTitle", "Home Features")]
        [Xunit.TraitAttribute("Description", "View Home Details")]
        public virtual void ViewHomeDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View Home Details", ((string[])(null)));
#line 31
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "Name",
                        "Fransic\'s Home"});
            table6.AddRow(new string[] {
                        "Address",
                        "Test Address"});
#line 32
 testRunner.Given("I create a home with the following data", ((string)(null)), table6, "Given ");
#line 36
 testRunner.When("I access the details of the last created home", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table7.AddRow(new string[] {
                        "Name",
                        "Fransic\'s Home"});
            table7.AddRow(new string[] {
                        "Address",
                        "Test Address"});
#line 37
 testRunner.Then("the following home should exists", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Update Home")]
        [Xunit.TraitAttribute("FeatureTitle", "Home Features")]
        [Xunit.TraitAttribute("Description", "Update Home")]
        public virtual void UpdateHome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update Home", ((string[])(null)));
#line 42
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "Name",
                        "Fransic\'s Home"});
            table8.AddRow(new string[] {
                        "Address",
                        "Test Address"});
#line 43
 testRunner.Given("I create a home with the following data", ((string)(null)), table8, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table9.AddRow(new string[] {
                        "Name",
                        "Hillary\'s Home"});
            table9.AddRow(new string[] {
                        "Address",
                        "Test Address 3"});
#line 47
 testRunner.And("I update the last home created with the following data", ((string)(null)), table9, "And ");
#line 51
 testRunner.When("I list the last 1 created homes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Address"});
            table10.AddRow(new string[] {
                        "Hillary\'s Home",
                        "Test Address 3"});
#line 52
 testRunner.Then("the following homes should exists", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Delete Home")]
        [Xunit.TraitAttribute("FeatureTitle", "Home Features")]
        [Xunit.TraitAttribute("Description", "Delete Home")]
        public virtual void DeleteHome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete Home", ((string[])(null)));
#line 56
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table11.AddRow(new string[] {
                        "Name",
                        "NotDelete\'s Home"});
            table11.AddRow(new string[] {
                        "Address",
                        "Test Address"});
#line 57
 testRunner.Given("I create a home with the following data", ((string)(null)), table11, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table12.AddRow(new string[] {
                        "Name",
                        "Trump\'s Home"});
            table12.AddRow(new string[] {
                        "Address",
                        "Test Address"});
#line 61
 testRunner.And("I create a home with the following data", ((string)(null)), table12, "And ");
#line 65
 testRunner.When("I delete the last home", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table13.AddRow(new string[] {
                        "Name",
                        "NotDelete\'s Home"});
            table13.AddRow(new string[] {
                        "Address",
                        "Test Address"});
#line 66
 testRunner.Then("should exists a home with data", ((string)(null)), table13, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                HomeFeaturesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                HomeFeaturesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
